# NovaMart - lookup definitions (REFERENCE / Module 5)
[novamart_products]
filename = novamart_products.csv

[http_status_lookup]
filename = http_status.csv

[threat_intel_ips]
filename = threat_intel_ips.csv
